config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  root to: "welcome_index#index", as: "/home"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "/profile", to: "user_profile#user_profile"
  get "/profile/edit", to: "user_profile#edit"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :validate_username

  validates :email,
        uniqueness: { message: " is already taken." },
        on: :some_action

  validates :password,
        presence: true,
        on: :some_action

  validates :password_confirmation,
        presence: { message: " must be provided" }


  def validate_username
    if username.length < 6
      errors.add(:username, "must be provided and have at least 6 characters")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_now
    else
      puts "SOMETHING WRONG WAS HEPPEND | WE CANT SEND YOU A TOKEN"
    end

    redirect_to home_path, notice: "If an account with that email was found, we have sent a link to reset your password."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, notice: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to new_user_session_path, notice: "Your password was reset successfully."
    else
      render :edit, notice: "Something went wrong with your password. Remember, passwords should be longer than 8 characters and should match."
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to home_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def user_profile
    @user = current_user
  end

  def edit

  end
end

app/controllers/welcome_index_controller.rb
class WelcomeIndexController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/welcome_index_helper.rb
module WelcomeIndexHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Network</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/password_reset/edit.html.erb
<div class="container mt-5">
    <div class="container-box">
        <div class="container-for-form">

            <h2 class="text-center mb-4">Reset your password</h2>

            <%= form_with model: @user,data: { turbo: false }, url: password_reset_edit_path(token: params[:token]) do |f| %>
                <div class="field">
                    <%= f.label :password, class:"form-label" %>
                    <%= f.password_field :password, autocomplete: "new-password", class:"form-control" %>
                </div>
                <div class="field">
                    <%= f.label :password_confirmation, class:"form-label" %>
                    <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control" %>
                </div>

                <% if f.object.errors.any? %>
                    <div class="mt-3">
                        <% f.object.errors.full_messages.each do |message| %>
                            <div class="d-flex gap-2 align-items-center">
                                <%= image_tag("Subtract.svg") %>
                                <p class="error-message"><%= message %></p>
                            </div>
                        <% end %>
                    </div>
                <% end %>

                <div class="mt-3">
                    <div class="d-flex justify-content-center">
                        <%= f.submit "Reset Password", class:"btn btn-dark" %>
                    </div>
                </div>
            <% end %>
            <% if notice.present? %>
                <div class="d-flex align"><%= notice %></div>
            <% end %>
        </div>
    </div>
</div>

app/views/password_reset/new.html.erb
<div class="container mt-5">
    <div class="container-box">
        <div class="container-for-form">

            <h2 class="text-center mb-4">Forgot your password?</h2>

            <%= form_with url: password_reset_path do |f| %>
                <div class="mb-3">
                    <%= f.label :email %>
                    <%= f.text_field :email, class:"form-control", placeholder:"user@email.com" %>
                </div>

                <div class="mb-3">
                    <div class="d-flex justify-content-center">
                        <%= f.submit "Reset Password", class:"btn btn-dark" %>
                    </div>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/user_profile/edit.html.erb
<h1>Edit Profile info</h1>

app/views/user_profile/user_profile.html.erb
<header class="header_container">
    <%= render template: "components/header" %>
</header>

<%= link_to "Edit", profile_edit_path, class:"btn btn-dark" %>

<h1>User Profile Page</h1>
<h2><%= @user.email %></h2>
<h2><%= @user.username %></h2>

app/views/welcome_index/index.html.erb
<%= stylesheet_link_tag "header", media: "all" %>

<header class="header_container">
    <%= render template: "components/header" %>
</header>

<div class="container">
    <% if notice.present? %>
        <p class="alert alert-secondary mt-4 mb-4"><%= notice %></p>
    <% end %>
</div>